#version: '3.8'

services:
  postgres:
    image: postgres:15-trixie
    container_name: portgres
    environment:
      # These ${VARIABLES} are read from the .env file in the same directory as docker-compose.yml
      POSTGRES_DB: respawn_market
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      # Format is: host_path : container_path
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  grpc-server-springboot-service:
      build:
        context: .
        dockerfile: java_projects/ReSpawnMarket/Dockerfile
      container_name: respawn-shichiya-grpc-server
      ports:
        - "8080:8080"
        - "6767:6767"

        # copy all application properties that use ${...} 
        # syntax to read from environment variables, as spring boot in the 
        # container won't have access to the .env file directly, 
        # but will read the .env variables passed in through docker-compose    
      environment:
        # --- Database (Matches application.properties placeholders) ---
        DB_URL: ${DOCKER_DB_URL}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_DRIVER: org.postgresql.Driver
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        SPRING_GRPC_SERVER_PORT: 6767

        # gRPC & Server SSL 
        IS_SSL_ENABLED: "true"
        KEYSTORE_LOCATION: ${RELATIVE_KEY_PATH}
        SSL_KEYSTORE_PATH: ${RELATIVE_KEY_PATH}
        KEYSTORE_PASSWORD: ${KEY_PASSWORD}
        SSL_KEYSTORE_PASSWORD: ${KEY_PASSWORD}
        KEY_PASSWORD: ${KEY_PASSWORD}
      
      volumes:
        # Mapped ./self_signed_cert (host) to /app/self_signed_certs (container)
        - ./self_signed_certs:/app/self_signed_certs:ro
      depends_on:
        postgres:
          condition: service_healthy